addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.6.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.13")
addSbtPlugin("com.heroku"                % "sbt-heroku"          % "2.1.4")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.5")
addSbtPlugin("com.typesafe.sbt"          % "sbt-twirl"           % "1.5.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-git"             % "1.0.0")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.10.0")
