//addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.3")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.4.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.10")
addSbtPlugin("com.heroku"                % "sbt-heroku"          % "2.1.4")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.6.0")
