name: deploy
on:
  release:
    types: [released]

jobs:
  deploy_docker:
    runs-on: ubuntu-20.04

    env:
      DOPE_MAXMIND_GEOIP_API_KEY: ${{ secrets.DOPE_MAXMIND_GEOIP_API_KEY }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-sbt-coursier-${{ hashFiles('**/build.sbt') }}

    - name: Install Docker
      run: |
        sudo apt-get install docker.io -y
  
    - name: Login to Docker
      run: sudo docker login --username=$DOCKER_USER  --password=$DOCKER_PASS

    - name: Compile
      run: |
        sudo make clean build

    - name: Publish Docker
      run: |
        sudo make push
  